# Generated by Django 5.0.2 on 2024-04-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0003_alter_budget_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget',
            field=models.FloatField(null=True),
        ),
    ]
